<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOsoFVvD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOsoFVvD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOsoFVvD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOsoFVvD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOsoFVvD\App_KernelDevDebugContainer([
    'container.build_hash' => 'OsoFVvD',
    'container.build_id' => '431f28f8',
    'container.build_time' => 1743433930,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOsoFVvD');
