<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8Hn6U7N\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8Hn6U7N/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8Hn6U7N.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8Hn6U7N\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8Hn6U7N\App_KernelDevDebugContainer([
    'container.build_hash' => '8Hn6U7N',
    'container.build_id' => '58eb1b05',
    'container.build_time' => 1743625807,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8Hn6U7N');
