<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX2Oh2LC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX2Oh2LC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX2Oh2LC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX2Oh2LC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX2Oh2LC\App_KernelDevDebugContainer([
    'container.build_hash' => 'X2Oh2LC',
    'container.build_id' => '6c0b70d4',
    'container.build_time' => 1744394372,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX2Oh2LC');
