security:
    # Password hashing configuration
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Fournisseur d'utilisateurs (pour récupérer les utilisateurs)
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: mail

    firewalls:
        # Désactiver l'authentification pour la route /api/login
        api_login:
            pattern: ^/api/login$
            security: false

        # Configuration du firewall pour l'API avec JWT
        api:
            pattern: ^/api/
            jwt: ~
            provider: app_user_provider
            entry_point: Lexik\Bundle\JWTAuthenticationBundle\Security\Http\Authentication\AuthenticationSuccessHandler

        # Accès pour les autres routes (profiler, etc.)
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider

    # Contrôle d'accès
    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, roles: ROLE_USER }
